attack() method problems.
CC abilities problems with effects.

Single target abilities causing exceptions??

Damaging Abilities can't do type advantage in execute method.

Leader ability not working for some reason.

ClassCastException casting Cover to Champion.???

pretty much all directional methods have a problem. ¯\_(ツ)_/¯

removeDamageable() method doesn't work.

The method "remove" in class "Root" should set the correct valueof
variable "condition".
if the champion already has another ROOT effect, then his condition
should remain ROOTED
after removing "Root" effect. expected:<ROOTED> but was:<ACTIVE>